### ISSUE TITLE
How to Configure Static IP Address on Ubuntu 18.04

### ISSUE THREAD

**Issue by liuty10** [CS-FreeStyle/10000-How-To-Do-in-CS#98]
```
sudo cp /etc/netplan/01-network-manager-all.yaml /etc/netplan/01-network-manager-all.yaml.bak
vim /etc/netplan/01-network-manager-all.yaml
```

```
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
     dhcp4: no
     addresses: [192.168.1.222/24]
     gateway4: 192.168.1.1
     nameservers:
       addresses: [8.8.8.8,8.8.4.4]
```
`
sudo netplan apply`
